// Svelte/src/App.svelte
<script>
  import UsernameInputReactive from "./components/UsernameInputReactive.svelte";
  import TaskList from "./components/TaskList.svelte";
</script>

<main>
  <h1> Ejemplo 1 de svelte reactive - Comprobador de usuarios</h1>
  <UsernameInputReactive />
  <br><br><br><br><br><br>
  <h1> Ejemplo 2 de svelte reactive - Lista de tareas</h1>
  <TaskList />
</main>

<style>
</style>

// Vue/src/App.vue
<script setup>
import UsernameInputRef from './components/UsernameInputRef.vue';
import UsernameInputReactive from './components/UsernameInputReactive.vue';

</script>

<template>
  <div id ="#app">
    <h1> Ejemplo ref </h1>
    <UsernameInputRef />
    <br><br><br><br><br><br>
    <h1> Ejemplo reactive </h1>
    <UsernameInputReactive />
  </div>
</template>
